// job.js
export const jobRoles = [
    "서버/백엔드 개발자",
    "프론트엔드 개발자",
    "풀 스택 개발자",
    "게임 클라이언트 개발자",
    "DBA",
    "개발 PM",
    "안드로이드 개발자",
    "IOS 개발자",
    "크로스플랫폼 앱 개발자",
    "빅데이터 엔지니어",
    "인공지능/머신러닝",
    "데브옵스 엔지니어",
    "QA/테스터",
    "보안 엔지니어",
    "네트워크 엔지니어",
    "클라우드 엔지니어",
    "블록체인 개발자",
    "VR/AR 개발자",
    "게임 서버 개발자",
    "영상 처리 개발자",
    "음성 인식 엔지니어",
    "IoT 개발자",
    "임베디드 소프트웨어 개발자",
    "로봇 소프트웨어 엔지니어",
    "IT 컨설턴트",
    "테크니컬 아키텍트",
    "데이터 엔지니어",

    "모바일 앱 개발자",
    "ERP 개발자"
];

export const skillStacks = [
    "AWS",
    "JavaScript",
    "C++",
    "C#",
    "React",
    "Python",
    "아키텍처",
    "칸반/스크럼",
    "Unix",
    "SQL",
    "JAVA",
    "Kotlin",
    "OpenCV",
    "R",
    "XML",
    "WAS",
    "Linux",
    "Spring",
    "HTML",
    "CSS",
    "TypeScript",
    "Vue.js",
    "Angular",
    "Node.js",
    "Django",
    "Flask",
    "Ruby on Rails",
    "Express.js",
    "MongoDB",
    "PostgreSQL",
    "Oracle DB",
    "Redis",
    "GraphQL",
    "Docker",
    "Kubernetes",
    "Terraform",
    "Ansible",
    "CI/CD",
    "Jenkins",
    "Git",
    "GitLab",
    "Apache Kafka",
    "Hadoop",
    "Spark",
    "TensorFlow",
    "PyTorch",
    "NLP",
    "Tableau",
    "Power BI",
    "MATLAB",
    "Unity",
    "Unreal Engine",
    "Objective-C",
    "Swift",
    "Figma",
    "Sketch",
    "Zeplin",
    "Bootstrap",
    "Tailwind CSS",
    "Webpack",
    "Babel",
    "SCSS",
    "Sass",
    "Elasticsearch",
    "Snowflake",
    "Firebase",
    "Azure",
    "OpenShift",
    "Rust",
    "Go",
    "Scala",
    "Perl"
];
